estery_project/estery_app/urls.py
from django.urls import path
from .import views
from django.contrib.auth import views as auth_view

urlpatterns = [

   path("home/", views.home, name='home'),
   path("", views.index, name='index'),
   path("index_admin/", views.index_admin, name='index_admin'),

   path('about/', views.about, name='about'),
   path('product/', views.product, name='product'),
   path('contact/', views.contact, name='contact'),

   path('login/', views.loginPage, name="login"),
   path('logout/', views.logoutUser, name="logout"),
    
   path('create_employee/', views.createEmployee, name="create_employee"),
   path('update_employee/<str:emp_id>/', views.updateEmployee, name='update_employee'),
   path('delete_employee/<str:emp_id>/', views.deleteEmployee, name='delete_employee'),

   path('create_sale/', views.create_sale, name='create_sale'),
   path('update_sale/<int:id>/', views.updateSale, name='update_sale'),
   path('delete_sale/<int:id>/', views.deleteSale, name='delete_sale'),

   path('create_expense/', views.createExpense, name='create_expense'),
   path('update_expense/<int:id>/', views.updateExpense, name='update_expense'),
   path('delete_expense/<int:id>/', views.deleteExpense, name='delete_expense'),

   path('create_purchase/', views.createPurchase, name='create_purchase'),
   path('update_purchase/<int:id>/', views.updatePurchase, name='update_purchase'),
   path('delete_purchase/<int:id>/', views.deletePurchase, name='delete_purchase'),

        
   path('employee/<str:emp_id>/', views.employee, name='employee'),

   path('all_sale/', views.allSale, name='all_sale'),
   path('all_expense/', views.allExpense, name='all_expense'),
   path('all_purchase/', views.allPurchase, name='all_purchase'),
   path('all_employee/', views.allEmployee, name='all_employee'),

   path('add_product/', views.add_product, name='add_product'),
   path('daily_report/', views.daily_report, name='daily_report'),

   #    path('deposit_csv/', views.deposit_csv, name='deposit_csv'),
   #    path('relative_csv/', views.relative_csv, name='relative_csv'),
   #    path('member_txt/', views.member_txt, name='member_txt'),   

   path('sales/', views.sales_view, name='sales'),
   path('all_sales/', views.SalesListView.as_view(), name='all_sales'),
   path('total_sales/', views.total_sales, name='total_sales'),

   path('image_upload/', views.image_upload_view, name='image_upload'),
   path('stock_upload/', views.stock_upload, name='stock_upload'),
   path('images/', views.ImageListView.as_view(), name='image_list'),
   path('stock/', views.StockListView.as_view(), name='stock_list'),   
   path('edit_image/<pk>/', views.edit_image, name='edit_image'),
   path('delete_image/<pk>/', views.delete_image, name='delete_image'),


]

estery_project/estery_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('estery_app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# config Admin Page
admin.site.site_header = "ESTERY FURNITURE PANEL"
admin.site.site_title = "ESTERY-WEBSITE"
admin.site.index_title = "Administration Area" 

estery_project/estery_app/models.py
from django.db import models
import datetime
from datetime import date  
from django.core.validators import MinValueValidator
from django.core.validators import MaxValueValidator

class Employee(models.Model):
    sex_choices = (("Male","male"), ("Female","Female"))
    emp_id =models.CharField(max_length=10, primary_key=True )
    full_name = models.CharField(max_length=200, null=False)
    sex = models.CharField(max_length=10,choices = sex_choices)
    telephone = models.PositiveIntegerField()
    date_of_birth = models.DateField(validators=[MaxValueValidator(datetime.date.today)])
    parent_name = models.CharField(max_length=200, null=False)
    parent_telephone = models.PositiveIntegerField()
    home_address = models.CharField(max_length=300) 
    Registered_date = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):

        return self.emp_id + " " +self.full_name

class Expense(models.Model):
    branch_choices =(("Kalerwe","Kalerwe"),("kireka","kireka"))

    purpose = models.CharField(max_length=300, null=False)
    amount = models.PositiveIntegerField()
    date_of_expense = models.DateField()
    branch = models.CharField(max_length=200, null=False, choices = branch_choices)
    person_responsible = models.ForeignKey(Employee, on_delete=models.SET_DEFAULT, default=None, null=False)
    image = models.ImageField(upload_to='expenses/%Y/%m/%d',blank=True)

    def __str__(self):
        return self.purpose +"  "+ str(self.amount)


class Purchase(models.Model):
    branch_choices =(("Kalerwe","Kalerwe"),("kireka","kireka"))

    item_name = models.CharField(max_length=300, null=False)
    quantity = models.PositiveIntegerField()
    amount = models.PositiveIntegerField()
    date_of_purchase = models.DateField()
    branch = models.CharField(max_length=30, null=False, choices = branch_choices)
    receipt_no = models.CharField(max_length=300)
    person_responsible = models.ForeignKey(Employee, on_delete=models.SET_DEFAULT, default=None, null=False)
    supplier_name = models.CharField(max_length=300, null=False)
    supplier_contact = models.PositiveIntegerField()
    image = models.ImageField(upload_to='images/%Y/%m/%d',blank=True)


class Sale(models.Model):
    branch_choices =(("Kalerwe","Kalerwe"),("kireka","kireka"))

    item_name = models.CharField(max_length=300, null=False)
    quantity = models.PositiveIntegerField()
    unit_price = models.PositiveIntegerField()
    date_of_sale = models.DateField()
    branch = models.CharField(max_length=30, null=False, choices = branch_choices)
    # receipt_no = models.CharField(max_length=300)
    person_responsible = models.ForeignKey(Employee, on_delete=models.SET_DEFAULT, default=None, null=False)
    customer_name = models.CharField(max_length=300, null=False)
    customer_contact = models.PositiveIntegerField()
    # receipt = models.ImageField(upload_to='deposits/%Y/%m/%d',blank=True)
    status = models.CharField(max_length=300)

    @property
    def total_amount(self):
    	total_amount = self.unit_price * self.quantity
    	return total_amount
    
class Stock(models.Model):
    date = models.DateField()
    item = models.CharField(max_length=255)
    quantity = models.DecimalField(max_digits=10, decimal_places=1)
    cost_price = models.DecimalField(max_digits=10, decimal_places=2, default=0, null=True)
    selling_price = models.DecimalField(max_digits=10, decimal_places=2, default=0, null=True)
    supplier_name = models.CharField(max_length=255)
    supplier_number = models.IntegerField()
    image = models.ImageField(upload_to='images/')

class Sales(models.Model):
    date = models.DateField()
    item = models.CharField(max_length=255)
    quantity = models.DecimalField(max_digits=10, decimal_places=1)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    cust_name = models.CharField(max_length=255)
    cust_number = models.IntegerField()
    image = models.ImageField(upload_to='images/')

    def item_total(self): 
        return self.quantity * self.amount 

class ImageModel(models.Model):
    image = models.ImageField(upload_to='images/')
    title = models.CharField(max_length=255)
    description = models.TextField()
    tags = models.CharField(max_length=255)

estery_project/estery_app/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.urls import reverse
from django.shortcuts import render, redirect, get_object_or_404
# from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .models import Employee,Sale,Expense,Purchase,Stock, ImageModel,Sales
from .models import *
from django.contrib.auth import authenticate, login, logout
from .forms import EmployeeForm,SaleForm,ExpenseForm,PurchaseForm,StockForm,SalesForm,ImageForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group
from django.db.models import Q
from django.db.models import Sum, Avg, Count,F
from django.views.generic import ListView
from .filters import PurchaseFilter,ExpenseFilter,SaleFilter
from django.db import connection
from django.db.models.expressions import RawSQL
from django.conf import settings
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
import csv
from django.db.models.functions import TruncDate


def index(request):
    return render(request, 'index.html')

def index_admin(request):
    return render(request, 'index_admin.html')

def about(request):
    return render(request, 'about.html')

def product(request):
    return render(request, 'product.html')

def contact(request):
    return render(request, 'contact.html')

@login_required(login_url='login')
def home(request):
    total_employees = Employee.objects.all().count() #aggregate(Count('member_id'))
    # pending_deposits = Deposit.objects.filter(status='pending').count()
    # approved_deposits = Deposit.objects.filter(status='Approved').count()
    # deposits = Deposit.objects.all().order_by("-date_created") 
    # myFilter = DepositFilter(request.GET, queryset=deposits)
    # deposits = myFilter.qs
    expenses_total = Expense.objects.all().aggregate(models.Sum('amount'))['amount__sum'] or 0 
    # savings_total = Deposit.objects.filter(status='approved').aggregate(models.Sum('total_amount'))['total_amount__sum'] or 0 
    # savings_total = Deposit.objects.filter(status='approved').aggregate(models.Sum('amount_cash'))['amount_cash__sum'] or 0 
    # savings_total = Deposit.objects.filter(status='approved').aggregate(models.Sum('amount_cash'))['amount_cash__sum'] or 0 
    # otherincome = OtherIncome.objects.aggregate(models.Sum('amount'))['amount__sum'] or 0

    # current_balance = savings_total + otherincome - expenses_total 

    # grand_total = savings_total + expenses_total + otherincome

    context = {
        # 'pending_deposits': pending_deposits,
        # 'approved_deposits': approved_deposits,
        'total_employees': total_employees, 
        # # 'total_savings': total_savings,
        # 'deposits': deposits,
        # 'myFilter': myFilter, 
        # 'current_balance': current_balance,
        # 'savings_total': savings_total,
        # 'expenses_total':expenses_total,
        # 'grand_total': grand_total,
        
        # 'otherincome':otherincome,
        
      }

    return render(request,'dashboard.html', context)
    

def index(request):
    context = {
        'variable1': 'Hello',
        'variable2': 'World',
    }
    return render(request, 'index.html', context)

    
class ImageListView(ListView):
    model = ImageModel
    template_name = 'image_list.html'
    context_object_name = 'images'

def employee(request, emp_id):
    employee = Employee.objects.get(emp_id=emp_id)
    # deposits = employee.deposit_set.all().order_by('-date_created')
    expenses = employee.expense_set.all().order_by('-date_of_expense')
    purchases = employee.purchase_set.all().order_by('-date_of_purchase')
    # used_total = employee.deposit_set.filter(status='Approved').aggregate(models.Sum('amount_used'))['amount_used__sum'] or 0
    # cash_total = employee.deposit_set.filter(status='Approved').aggregate(models.Sum('amount_cash'))['amount_cash__sum'] or 0
    # ind_fine = member.fine_set.filter(status='unpaid').aggregate(models.Sum('amount'))['amount__sum'] or 0
    # myFilter = DepositFilter(request.GET, queryset=deposits)
    # deposits = myFilter.qs
    
    context = {
                'employee': employee, 
                # 'deposits': deposits, 
                'purchases':purchases,
                'expenses':expenses,
                # 'used_total':used_total,
                # 'myFilter': myFilter,
                # 'cash_total': cash_total,
    }

    return render(request, 'emp_report.html', context)

def loginPage(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect("index_admin")
        else: 
            messages.info(request, "Username or password is incorrect")

    context = {}
    return render(request, 'login.html', context)

def logoutUser(request):
    logout(request)
    return redirect('/')

def createEmployee(request):
    form = EmployeeForm()
    if request.method == "POST":
        form = EmployeeForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("/")

    context = {'form': form}
    return render(request, 'employee_form.html', context)

def updateEmployee(request, emp_id):

    employee = Employee.objects.get(emp_id=emp_id)
    form = EmployeeForm(instance=employee)

    if request.method == "POST":
        form = EmployeeForm(request.POST, instance=employee)
        if form.is_valid():
            form.save()
            return redirect('/')
    context = {'form': form}
    return render(request, 'employee_form.html', context) 
    

def deleteEmployee(request, emp_id):
    employee = Employee.objects.get(emp_id=emp_id)
    if request.method == "POST":
        employee.delete()
        return redirect('home')

    context = {'item': employee } 

    return render(request, 'delete_employee.html', context) 

def allEmployee(request):

    employee_list = Employee.objects.all()  
         

    context = {
                'employee_list': employee_list, 
                    
        }  

    return render(request, 'all_employee.html', context )


def create_sale(request):
    if request.method == 'POST':
        form = SaleForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home')
    else:
        form = SaleForm()
    return render(request, 'create_sale.html', {'form': form})


def updateSale(request, id):
    sale = Sale.objects.get(id=id)
    form = SaleForm(instance=sale)

    if request.method == "POST":
        form = SaleForm(request.POST, instance=sale)
        if form.is_valid():
            form.save()
            return redirect('/')

    context = {'form': form } 

    return render(request, 'create_sale.html', context)         

def deleteSale(request, id):
    sale = Sale.objects.get(id=id)
    if request.method == "POST":
        sale.delete()
        return redirect('/')

    context = {'item': sale } 

    return render(request, 'delete_sale.html', context)

def allSale(request):
    search_sale = request.GET.get('search')
    if search_sale:

        sales = Sale.objects.filter(Q(amount__icontains=search_sale) |
                             Q(purpose__icontains=search_sale) |
                             Q(date_created__icontains=search_sale))
    else:
        # If not searched, return default members
        sales = Sale.objects.all().order_by("-date_of_sale") 
        myFilter = SaleFilter(request.GET, queryset=sales)
        sales = myFilter.qs   
         
        context = {'sales': sales,
                    'myFilter': myFilter
        } #'members': members} 

    return render(request, 'all_sale.html', context )



def createExpense(request):
    if request.method == 'POST':
        form = ExpenseForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/')
    else:
        form = ExpenseForm()
    return render(request, 'create_expense.html', {'form': form})


def updateExpense(request, id):
    expense = Expense.objects.get(id=id)
    form = ExpenseForm(instance=expense)

    if request.method == "POST":
        form = ExpenseForm(request.POST, instance=expense)
        if form.is_valid():
            form.save()
            return redirect('home')

    context = {'form': form } 

    return render(request, 'create_expense.html', context)         

def deleteExpense(request, id):
    expense = Expense.objects.get(id=id)
    if request.method == "POST":
        expense.delete()
        return redirect('home')

    context = {'expense': expense } 

    return render(request, 'delete_expense.html', context) 

def allExpense(request):
    search_expense = request.GET.get('search')
    if search_expense:
        expenses = Expense.objects.filter(
                             Q(purpose__icontains=search_expense) |
                             Q(date_created__icontains=search_expense))
    else:
        # If not searched, return default members
        expenses = Expense.objects.all().order_by("-date_of_expense") 
        myFilter = ExpenseFilter(request.GET, queryset=expenses)
        expenses = myFilter.qs   
         
        context = {
                    'expenses': expenses,
                    'myFilter': myFilter
                    }
    return render(request, 'all_expenses.html', context )


def createPurchase(request):
    if request.method == 'POST':
        form = PurchaseForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/')
    else:
        form = PurchaseForm()

estery_project/estery_app/templates/about.html
<!-- {% extends 'main.html' %} -->
{% load crispy_forms_tags %}
{% load static %}

{% block content %}

	<style>
    .navbar {
        position: sticky;
        top: 0;
        background-color: #333;
        color: white;
        padding: 10px;
        z-index: 100; /* Ensure it stays above other elements */
    }
	</style>

<!-- Boostrap CSS CDN -->    
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'style.css' %}">
	<section class="sub-header">
		<nav class="navbar">
			<!-- <a href="#"><img src="{% static 'images/logo2.jpeg' %}" style="width: 80%; height: 40px; border-radius: 50%;"></a> -->
			<div class="nav-links" id="navLinks" style="background-color:blueviolet; border-radius: 10px;">
				<i class="fa fa-times" onclick="hideMenu()"></i>
				<ul>
					<li><a href="{% url 'index' %}">HOME</a></li>
					<li><a href="{% url 'about' %}">ABOUT</a></li>
					<li><a href="{% url 'image_list' %}">PRODUCTS</a></li>
					<li><a href="{% url 'contact' %}">CONTACT</a></li>
           <li><a href="{% url 'login' %}">LOGIN</a></li>
				</ul>
			</div>
			<i class="fa fa-bars" onclick="showMenu()"></i>
		</nav>
</section>
<!-- <div class="text-box"><br> -->
  <br>
<h1 align="center">About Us</h1>
<!-- <p>Welcome to Estery Furniture Company</p> -->
<p style="background-color:grey; color: white; ">At Estery Furniture, we're passionate about creating beautiful, functional, and sustainable furniture pieces that bring joy to our customers' homes.<br> Our mission is to provide exceptional quality, comfort, and style, while promoting environmentally responsible practices.
</p>
	
<!-- -----------------equal height section ------- -->
<br>
<div class="row row-cols-1 row-cols-md-2 g-4">
  <div class="col">
    <div class="card h-100">
      <img src="{% static 'images/logo2.jpeg' %}" style="width: 100%; height: 350px; " />
    </div>
  </div>
  <div class="col">
    
        <h4 class="card-title" style="align-content: center; ">Our Story</h4>
        <!-- <p class="card-text">This is a short card.</p> -->

          <p>At Estery Furniture, we're passionate about creating beautiful, functional, and sustainable furniture pieces<br> that bring joy to our customers' homes.<br> Our mission is to provide exceptional quality, comfort, and style, while promoting environmentally responsible practices.
          </p>
      </div>
    </div>
  </div>
</div>
<!-- -----------------equal height section ------- -->

<!-- -----------------equal height section ------- -->
<br>
<div class="row row-cols-1 row-cols-md-2 g-4">
  <div class="col">
    <div class="card h-100">
      <!-- <img src="images/logo2.jpg"/> -->
      <div class="card-body">
        <h4 class="card-title">Our Values</h4>
        <p class="card-text">          
          At Estery Furniture Company, we're guided by the following values:
          - Quality: We're dedicated to crafting furniture pieces that are built to last, using only the finest materials and time-tested techniques.
          - Sustainability: We believe in reducing our environmental footprint, sourcing materials responsibly, and promoting eco-friendly practices throughout our operations.
          - Comfort: We design our furniture to provide optimal comfort, ensuring that every piece is both beautiful and functional.
          - Style: We're inspired by the latest design trends, while also respecting timeless classics, to create furniture pieces that are both stylish and versatile.

        </p>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="card h-100">
      <img src="{% static 'images/logo4.jpeg' %}" style="width: 100%; height: 350px;"/>
      <!-- <div class="card-body">
        <h5 class="card-title">Card title</h5>
        <p class="card-text">This is a short card.</p>
      </div> -->
    </div>
  </div>
</div>
<!-- -----------------equal height section ------- -->

<section class="services">
<div class="row1">
  <h1 align="center">Our Team </h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
    tempor incididunt ut labore et dolore magna aliqua.</p>
    <div class="column">
      <!-- <h1>Image 1</h1> -->
      <img src="{% static 'images/bg.jpeg' %}" style="width: 100%;">
      <p>Your home, your style, our furniture. We're passionate about helping you create a space that reflects your personality and meets your needs..</p>
    </div>
    <div class="column">
      <!-- <h1>Image 2</h1> -->
      <img src="{% static 'images/1.jpeg' %}" style="width: 100%;">
      <p>Your home, your style, our furniture. We're passionate about helping you create a space that reflects your personality and meets your needs.</p>
    </div>
    <div class="column">
      <!-- <h1>Image 3</h1> -->
      <img src="{% static 'images/chair.jpeg' %}" style="width: 100%;">
      <p>Your home, your style, our furniture. We're passionate about helping you create a space that reflects your personality and meets your needs.</p>
    </div>
</div>
</section>

<section class="cta">
    <h1>Visit Our Branches</h1>
    <p>Our branches are designed to inspire and delight, with a vast selection of stylish <br>and functional furniture pieces on display.</p>
    <a href="contact.html" class="hero-btn">Contact Us</a>
    
  </section>
	<hr>
	<section class="footer">
		<div class="icons">
			<i class="fa fa-instagram"></i>
			<i class="fa fa-facebook"></i>
			<i class="fa fa-twitter"></i>
			<i class="fa fa-youtube"></i>
		</div>
		<p>Made with <i class="fa fa-heart-o"></i> by Chriscode Academy!!</p>
	</section>


<!-- js for togglin the menu -->

<script>
	var navLinks = document.getElementById('navLinks');

	function showMenu() {
		navLinks.style.right = "0";

	}

	function hideMenu() {
		navLinks.style.right = "-200px";

	}

</script>
	
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
{% endblock content %}

estery_project/estery_app/templates/add_product.html
{% load crispy_forms_tags %}
{% load static %}


{% block content  %}
    <link rel="stylesheet" href="#">
    <div class="container" >
    <br>
    <h3></h3>
    <form method="POST"  action="" >
      {% csrf_token %}
      <fieldset class="form-group">
            <legend class="border-bottom mb-4" style="color: darkblue; text-align: center;">Enter a new Asset </legend>
            {{ form|crispy }}
        </fieldset><br>
        <div class="form-group" id="signup-button" align="center">
            <a class="btn btn-lg btn-success" href="#">Home</a>
            <button class="btn btn-lg btn-primary">Submit</button>
        </div>
    </form>
{% endblock content %}

estery_project/estery_app/templates/all_otherincome.html
<!-- {% extends 'main.html' %}

{% block content %}
<br>
<div class="row">
    <div class="col">
        <div class="col-md">
            <h5 align="center"> MEMBERS: </h5>
            <hr>
            <div class="card card-body">
                <a class="btn btn-sm btn-block bg-primary" style="color: white;"  href="{% url 'create_otherincome' %}"> Add New Income Source </a>
                <table class="table table-sm table-hover">
                    <tr>
                        <th>ID</th>
                         <th>Date of Earnings</th>
                        <th>Source Name</th>
                        <th>Amount</th>
                       
                        <th>Update</th>
                        <th>Delete</th>
                    </tr>

                    {% for member in otherincome_list %}
                    <tr>
                        <td>{{member.id}}</td>
                        <td>{{member.date_of_income}}</td>
                        <td>{{member.source}}</td>
                        <td>{{member.amount}}</td>
                        

                        <td><a class="btn btn-sm btn-primary" href="{% url 'update_otherincome' member.id %}">update</a></td>
                        <td><a class="btn btn-sm btn-danger" href="{% url 'delete_otherincome' member.id %}">Delete</a></td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
{% endblock content %} -->

estery_project/estery_app/templates/all_purchases.html
{% extends 'main.html' %}
{% load static %}
{% load humanize %}

{% block content %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
 
<br>
<!-- <div class="row">
    <div class="col">
        <h3 align="center">Search through Expenses:</h3>
        <div class="card card-body">
            <form method="get">
                {{expenseFilter.form}}
                <button class="btn btn-primary" type="submit">Search</button>
            </form>
        </div>
    </div>
</div> -->
 <div class = "col-md-11 text-center">
    <div class="card card-body">
        <h3 id="header-h2">Stock List</h3>
        <a class="btn btn-primary btn-block" href="{% url 'create_purchase' %}"> Add a New Stock Item</a><p></p>
        <table class="table table-bordered border-primary table-hover">
            
                <!-- <th> ID</th> -->
                <th>DATE</th>
                <th>ITEM(S)</th>
                <th>QUANTITY</th>
                <th>AMOUNT</th>
                <th>RECEIPT NO</th>
                <th>BRANCH</th>
                
                <th>STAFF</th>
                <th>UPDATE</th>
                <th>REMOVE</th>
            
            {% for x in purchase_list %}
            <tr>
                <!-- <td>{{ x.id }}</td> -->
                <td>{{ x.date_of_purchase }}</td>
                <td>{{ x.item_name }}</td>  
                <td>{{ x.quantity }}</td>
                <!-- <td>{{ x.unit_price }}</td>               -->
                <td>{{ x.amount|floatformat|intcomma }}</td>
                <td>{{ x.receipt_no}}</td>
                <td>{{ x.branch }}</td>
                <td>{{ x.person_responsible}}</td>
                <!-- <td>{{ x.image}}</td> -->
                
                

                <td><a class="btn btn-sm btn-info" href="{% url 'update_purchase' x.id  %}">Update</a></td>
                <td><a class="btn btn-sm btn-danger" href="{% url 'delete_purchase' x.id  %}">Delete</a></td>
            </tr>
            {{ x.image}}
            {% endfor %}
            
        </table>
    </div><br>
</div>

 <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/js/bootstrap.bundle.min.js" integrity="sha384-j1CDi7MgGQ12Z7Qab0qlWQ/Qqz24Gc6BM0thvEMVjHnfYGF0rmFCozFSxQBxwHKO" crossorigin="anonymous"></script>           
{% endblock content %}

estery_project/estery_app/templates/dashboard.html
{% extends 'main.html' %}

{% block content %}
{% include 'status.html' %}


<br>
<hr>
<h6 align="center" ><strong>@Estery Furniture 2025 </h6>

{% endblock content %}